
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='lunavl',
    version='0.0.0',
    description='Python interface for VisionLabs Luna platform',
    python_requires='>=3.5',
    project_urls={'repository': 'https://github.com/matemax/lunasdk'},
    author='VisionLabs',
    author_email='m.limonov@visionlabs.ru',
    packages=['examples', 'examples.sdk_examples', 'lunavl', 'lunavl.sdk', 'lunavl.sdk.errors', 'lunavl.sdk.estimators', 'lunavl.sdk.estimators.face_estimators', 'lunavl.sdk.faceengine', 'lunavl.sdk.image_utils'],
    package_data={},
    install_requires=['numpy', 'requests'],
    extras_require={'dev': ['pytest>=4.4', 'pytest-subtests', 'sphinx>=2.0.0', 'sphinx-autodoc-typehints']},
)
